""" THIS IS AN AUTOMATICALLY GENERATED FILE!"""
from __future__ import print_function
import json
from engine import primitives
from engine.core import requests
from engine.errors import ResponseParsingException
from engine import dependencies
req_collection = requests.RequestCollection([])
# Endpoint: /nf-instances, method: Get
request = requests.Request([
    primitives.restler_static_string("GET "),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("nnrf-disc"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("v1"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("nf-instances"),
    primitives.restler_static_string("?"),
    primitives.restler_static_string("target-nf-type="),
    primitives.restler_fuzzable_group("target-nf-type", ['NRF','UDM','AMF','SMF','AUSF','NEF','PCF','SMSF','NSSF','UDR','LMF','GMLC','5G_EIR','SEPP','UPF','N3IWF','AF','UDSF','BSF','CHF','NWDAF','PCSCF','CBCF','HSS','UCMF','SOR_AF','SPAF','MME','SCSAS','SCEF','SCP']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("requester-nf-type="),
    primitives.restler_fuzzable_group("requester-nf-type", ['NRF','UDM','AMF','SMF','AUSF','NEF','PCF','SMSF','NSSF','UDR','LMF','GMLC','5G_EIR','SEPP','UPF','N3IWF','AF','UDSF','BSF','CHF','NWDAF','PCSCF','CBCF','HSS','UCMF','SOR_AF','SPAF','MME','SCSAS','SCEF','SCP']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("requester-nf-instance-id="),
    primitives.restler_fuzzable_uuid4("566048da-ed19-4cd3-8e0a-b7e0e1ec4d72", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("service-names="),
    primitives.restler_fuzzable_group("", ['nnrf-nfm','nnrf-disc','nnrf-oauth2','nudm-sdm','nudm-uecm','nudm-ueau','nudm-ee','nudm-pp','nudm-niddau','nudm-mt','namf-comm','namf-evts','namf-mt','namf-loc','nsmf-pdusession','nsmf-event-exposure','nausf-auth','nausf-sorprotection','nausf-upuprotection','nnef-pfdmanagement','nnef-smcontext','nnef-eventexposure','npcf-am-policy-control','npcf-smpolicycontrol','npcf-policyauthorization','npcf-bdtpolicycontrol','npcf-eventexposure','npcf-ue-policy-control','nsmsf-sms','nnssf-nsselection','nnssf-nssaiavailability','nudr-dr','nudr-group-id-map','nlmf-loc','n5g-eir-eic','nbsf-management','nchf-spendinglimitcontrol','nchf-convergedcharging','nchf-offlineonlycharging','nnwdaf-eventssubscription','nnwdaf-analyticsinfo','ngmlc-loc','nucmf-provisioning','nucmf-uecapabilitymanagement','nhss-sdm','nhss-uecm','nhss-ueau','nhss-ims-sdm','nhss-ims-uecm','nhss-ims-ueau','nsepp-telescopic','nsoraf-sor','nspaf-secured-packet']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("requester-nf-instance-fqdn="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("target-plmn-list="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("requester-plmn-list="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("target-nf-instance-id="),
    primitives.restler_fuzzable_uuid4("566048da-ed19-4cd3-8e0a-b7e0e1ec4d72", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("target-nf-fqdn="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("hnrf-uri="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("snssais="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("requester-snssais="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("plmn-specific-snssai-list="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("dnn="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("nsi-list="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("smf-serving-area="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("tai="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("amf-region-id="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("amf-set-id="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("guami="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("supi="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("ue-ipv4-address="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False, examples=["198.51.100.1"]),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("ip-domain="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("ue-ipv6-prefix="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False, examples=["2001:db8:abcd:12::0/64"]),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("pgw-ind="),
    primitives.restler_fuzzable_bool("true"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("pgw="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("gpsi="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("external-group-identity="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("internal-group-identity="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("pfd-data="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("data-set="),
    primitives.restler_fuzzable_group("data-set", ['SUBSCRIPTION','POLICY','EXPOSURE','APPLICATION']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("routing-indicator="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("group-id-list="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("dnai-list="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("pdu-session-types="),
    primitives.restler_fuzzable_group("", ['IPV4','IPV6','IPV4V6','UNSTRUCTURED','ETHERNET']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("event-id-list="),
    primitives.restler_fuzzable_group("", ['LOAD_LEVEL_INFORMATION','NETWORK_PERFORMANCE','NF_LOAD','SERVICE_EXPERIENCE','UE_MOBILITY','UE_COMMUNICATION','QOS_SUSTAINABILITY','ABNORMAL_BEHAVIOUR','USER_DATA_CONGESTION']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("nwdaf-event-list="),
    primitives.restler_fuzzable_group("", ['SLICE_LOAD_LEVEL','NETWORK_PERFORMANCE','NF_LOAD','SERVICE_EXPERIENCE','UE_MOBILITY','UE_COMMUNICATION','QOS_SUSTAINABILITY','ABNORMAL_BEHAVIOUR','USER_DATA_CONGESTION']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("supported-features="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("upf-iwk-eps-ind="),
    primitives.restler_fuzzable_bool("true"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("chf-supported-plmn="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("preferred-locality="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("access-type="),
    primitives.restler_fuzzable_group("access-type", ['3GPP_ACCESS','NON_3GPP_ACCESS']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("limit="),
    primitives.restler_fuzzable_int("1"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("required-features="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("complex-query="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("max-payload-size="),
    primitives.restler_fuzzable_int("1"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("atsss-capability="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("upf-ue-ip-addr-ind="),
    primitives.restler_fuzzable_bool("true"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("client-type="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("lmf-id="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("an-node-type="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("rat-type="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("preferred-tai="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("preferred-nf-instances="),
    primitives.restler_fuzzable_uuid4("566048da-ed19-4cd3-8e0a-b7e0e1ec4d72", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("target-snpn="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("af-ee-data="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("w-agf-info="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("tngf-info="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("twif-info="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("target-nf-set-id="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("target-nf-service-set-id="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("nef-id="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("notification-type="),
    primitives.restler_fuzzable_group("notification-type", ['N1_MESSAGES','N2_INFORMATION','LOCATION_NOTIFICATION','DATA_REMOVAL_NOTIFICATION','DATA_CHANGE_NOTIFICATION','LOCATION_UPDATE_NOTIFICATION']  ,quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("serving-scope="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("imsi="),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("preferred-api-versions="),
    primitives.restler_fuzzable_object("{ \"fuzz\": false }"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("v2x-support-ind="),
    primitives.restler_fuzzable_bool("true"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("redundant-gtpu="),
    primitives.restler_fuzzable_bool("true"),
    primitives.restler_static_string("&"),
    primitives.restler_static_string("redundant-transport="),
    primitives.restler_fuzzable_bool("true"),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: 127.0.0.10:8000\r\n"),
    primitives.restler_static_string("Accept-Encoding: "),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("\r\n"),
    primitives.restler_static_string("If-None-Match: "),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),

],
requestId="/nf-instances"
)
req_collection.add_request(request)

# Endpoint: /searches/{searchId}, method: Get
request = requests.Request([
    primitives.restler_static_string("GET "),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("nnrf-disc"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("v1"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("searches"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: 127.0.0.10:8000\r\n"),
    primitives.restler_static_string("Accept-Encoding: "),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),

],
requestId="/searches/{searchId}"
)
req_collection.add_request(request)

# Endpoint: /searches/{searchId}/complete, method: Get
request = requests.Request([
    primitives.restler_static_string("GET "),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("nnrf-disc"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("v1"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("searches"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("complete"),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: 127.0.0.10:8000\r\n"),
    primitives.restler_static_string("Accept-Encoding: "),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),

],
requestId="/searches/{searchId}/complete"
)
req_collection.add_request(request)
